Plug 'drewtempelmeyer/palenight.vim'
Plug 'rakr/vim-one'
Plug 'christoomey/vim-tmux-navigator'
Plug 'scrooloose/nerdcommenter'
Plug 'terryma/vim-multiple-cursors'
Plug 'editorconfig/editorconfig-vim'
